import { test, expect } from 'playwright/test'

test('Gateway can be played by keyboard; heat and tamper remain distinct; demo opens workspace', async ({ page }, info) => {
  await page.goto(`/preview.html?theme=${info.project.use.colorScheme === 'dark' ? 'dark' : 'light'}`)
  await expect(page.getByRole('heading', { name: 'Bắt đầu từ nguồn gốc.' })).toBeVisible()
  const parcel = page.getByRole('button', { name: /Kiện hàng tại/ })
  await parcel.scrollIntoViewIfNeeded()
  const handle = await parcel.boundingBox()
  const map = await page.locator('.playground-map > svg').boundingBox()
  await page.mouse.move(handle.x + handle.width / 2, handle.y + handle.height / 2)
  await page.mouse.down()
  await page.mouse.move(map.x + map.width * 580 / 640, map.y + map.height * 70 / 350, { steps: 16 })
  await page.mouse.up()
  await expect(page.getByRole('slider')).toHaveValue('3')
  await parcel.focus()
  await page.keyboard.press('End')
  await expect(page.getByRole('slider')).toHaveValue('3')
  await page.keyboard.press('Home')
  await expect(page.getByRole('slider')).toHaveValue('0')
  await page.getByRole('button', { name: 'Cho nhiệt độ tăng', exact: true }).click()
  await expect(page.locator('.playground-evidence-heading')).toContainText('Bằng chứng hợp lệ')
  await page.getByRole('button', { name: 'Thử sửa dữ liệu', exact: true }).click()
  await expect(page.locator('.playground-evidence-heading')).toContainText('Hash không khớp')
  await page.locator('.playground-hash-detail summary').click()
  const hashes = await page.locator('.hash-reading code').allTextContents()
  expect(hashes).toHaveLength(2)
  expect(hashes[0]).toMatch(/^[a-f0-9]{64}$/)
  expect(hashes[1]).not.toBe(hashes[0])
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBeTruthy()
  await page.screenshot({ path: info.outputPath('gateway.png'), fullPage: true, animations: 'disabled' })
  await info.attach('gateway', { path: info.outputPath('gateway.png'), contentType: 'image/png' })
  await page.getByRole('button', { name: /^Vào demo/ }).first().click()
  await expect(page.locator('.workspace-shell')).toBeVisible()
})

test('Gateway native required fields, synthetic credential request, API error focus and logout', async ({ page }, info) => {
  await page.goto(`/preview.html?theme=${info.project.use.colorScheme === 'dark' ? 'dark' : 'light'}`)
  await page.getByRole('button', { name: 'Mở workspace', exact: true }).click()
  await expect(page.getByLabel('Mật khẩu', { exact: false })).toHaveAttribute('aria-invalid', 'true')
  await page.getByRole('checkbox', { name: 'API 503 tổng hợp' }).check()
  await page.getByLabel('Mật khẩu', { exact: false }).fill('QA input only')
  await page.getByRole('button', { name: 'Mở workspace', exact: true }).click()
  await expect(page.locator('.gateway-error')).toContainText('503')
  await expect(page.locator('.gateway-error')).toBeFocused()
  await page.getByRole('checkbox', { name: 'API 503 tổng hợp' }).uncheck()
  await page.getByRole('button', { name: 'Mở workspace', exact: true }).click()
  await expect(page.locator('.workspace-shell')).toBeVisible()
  if (info.project.use.viewport.width <= 680) await page.getByLabel('Tài khoản và phiên làm việc').click()
  await page.getByRole('button', { name: 'Đăng xuất', exact: true }).click()
  await expect(page.locator('.secure-gateway')).toBeVisible()
  await page.reload()
  await expect(page.locator('.secure-gateway')).toBeVisible()
})
